### ISSUE TITLE
[Bug] Changing any setting in item, block, or biome configs causes CTD 1.18.2

### ISSUE THREAD

**Issue by entusiastaIA** [quiqueck/BetterNether#70]
### What happened?

In 1.18.2 doing changes as simple as setting ruby sword to false causes CTD on launch and altering biomes settings causes CTD on world creation screen.

### BetterNether

1.18.2 latest

### BCLib

1.18.2 latest

### Minecraft

1.18.2

### Relevant log output

```shell
No log is created, just opening and closing of the launcher/game
```

**Comment by quiqueck** [comment]
Thanks for reporting.

Not all changes to those configs are valid. For example, if you disable ruby ore, you will also need to disable anything that depends on it. Otherwise the game will crash.

When it crashes it should also generate a separate crash-file (not the latest.log) could you maybe attach one of those? Without any logs there is not much I can do :(

**Comment by entusiastaIA** [comment]
I have reinstalled BetterNether to force the crash (I am troubleshooting some other unrelated problems, so I am uninstalling most of my setup right now haha).

However, as I told you, it is a matter of altering anything as far as I have seen... haven't done lots of atempts, but just setting to false Ruby_Sword seems to be enough to get the crash, which should not be related to anything as far as I know. Here we go with the log, it is stil warm (I just changed Ruby Sword to false to force the crash):
[2022-10-14-6.log](https://github.com/quiqueck/BetterNether/files/9781310/2022-10-14-6.log)


Sorry for not beeing mor supportive, I am trying to fix some random CTDs I don't yet know which mod are them from.
