### ISSUE TITLE
[Bug] Rubies disappear when Shipwreck loot table is messed with?

### ISSUE THREAD

**Issue by Dmast3rRey** [quiqueck/BetterNether#95]
### What happened?

I stumbled upon this by accident while messing with the mod *Loot Config*.

Using code I found on the Loot Config Discord server, I recreated the vanilla Shipwreck loot table, minus the *Buried Treasure Map*, as it would essentially crash the server, when trying to look for a potential location, on a custom-made world.

Basically, the below posted chunk of code simply creates a new loot table but, without the existence of the Buried Treasure Map item in it. Then, through Loot Config, we can simply replace the vanilla version of the loot table.
`{ "LoadPoolsAtRuntime": true, "NameDefinitions": { }, "LootPoolDefinitions": { "remove_treasure_map": { "MinRolls": 3, "MaxRolls": 3, "RollSuccessChance": 1.0, "LootingRollSuccessModifier": 0, "MinBonusRolls": 0, "MaxBonusRolls": 0, "Conditions": { }, "Entries": { "minecraft:compass": [1, 1], "minecraft:map": [1, 1], "minecraft:clock": [1, 1], "minecraft:paper": [5, 20], "minecraft:feather": [3, 10], "minecraft:book": [3, 5] } } } }`

Inexplicably, this also causes Rubies to stop dropping when mining the Better Nether Ruby Ore. However, you will still get experience clumps, which shows that the ore itself isn't bugged but, only the Ruby item itself does not drop anymore.

I have tried to completely remove the Loot Config and, Rubies made a swift return into the game.

After the above mentioned, I wish to ask, are Rubies somehow related to the Shipwreck loot table in the Vanilla bit of the game? Could another issue exist? 

### BetterNether

7.1.2

### BCLib

2.1.4

### Fabric API

0.68.0

### Fabric Loader

0.14.10

### Minecraft

1.19.2

**Comment by quiqueck** [comment]
No, they are not.

But all our ores use some loot-table related code that checks if there was a loot-table defined (in for example a DataPack), if it was, then we use that one. Otherwise we perform the default behaviour.

So I would guess, that Loot Config somehow returns an empty loot-table for our ores? Could you maybe test this by defining any other loot-table (for example for basic stone), and see if that also has an impact on ruby.

Btw. if my theory is right, cincinnasite-ore should not drop anything either...
